/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package OOPProcessing;

import processing.core.PApplet;

public class App extends PApplet {
    public static final int WIDTH=1280;
    public static final int HEIGHT=720;

    public class Ball{
        private static final int DIAMETER = 100;
        private int ballNumber;
        public static int xCounter;

        Ball(int ballNumber){
            this.ballNumber = ballNumber;
        }

        public void drawBall() {
            int ballXCoordinate, ballYCoordinate;

            ballXCoordinate = (xCounter*ballNumber)%WIDTH;
            ballYCoordinate = (ballNumber * HEIGHT) / 5;

            ellipse(ballXCoordinate, ballYCoordinate, DIAMETER, DIAMETER);
        }

    }
    private Ball ball1, ball2, ball3, ball4;

    @Override
    public void settings() {
        super.settings();
        size(WIDTH, HEIGHT);
    }

    @Override
    public void setup() {
        ball1 = new Ball(1);
        ball2 = new Ball(2);
        ball3 = new Ball(3);
        ball4 = new Ball(4);
    }

    @Override
    public void draw() {
        paintWhite();

        ball1.drawBall();
        ball2.drawBall();
        ball3.drawBall();
        ball4.drawBall();

        nextFrame();
    }

    private void nextFrame() {
        Ball.xCounter++;
    }

    private void paintWhite() {
        background(255);
    }

    public static void main(String[] args) {
        PApplet.main("OOPProcessing.App", args);
    }
}

